alias pyvenv="python -m venv .venv && source .venv/bin/activate && echo .venv/ >> .gitignore"
alias prisma="bunx prisma"
alias prismaup="bunx prisma generate && bunx prisma db push --accept-data-loss"
alias expo="bunx expo"
alias pkill="pm2 kill"
alias ts="bunx ts-node"